# Form implementation generated from reading ui file 'review_window.ui'
#
# Created by: PySide6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_ReviewDialog(object):
    def setupUi(self, ReviewDialog):
        ReviewDialog.setObjectName("ReviewDialog")
        ReviewDialog.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReviewDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.enhanced_text_edit = QtWidgets.QPlainTextEdit(parent=ReviewDialog)
        self.enhanced_text_edit.setReadOnly(True)
        self.enhanced_text_edit.setObjectName("enhanced_text_edit")
        self.verticalLayout.addWidget(self.enhanced_text_edit)
        self.label = QtWidgets.QLabel(parent=ReviewDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setIndent(1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.accept_button = QtWidgets.QPushButton(parent=ReviewDialog)
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout.addWidget(self.accept_button)
        self.decline_button = QtWidgets.QPushButton(parent=ReviewDialog)
        self.decline_button.setObjectName("decline_button")
        self.horizontalLayout.addWidget(self.decline_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ReviewDialog)
        QtCore.QMetaObject.connectSlotsByName(ReviewDialog)

    def retranslateUi(self, ReviewDialog):
        _translate = QtCore.QCoreApplication.translate
        ReviewDialog.setWindowTitle(_translate("ReviewDialog", "Review Enhanced Prompt"))
        self.label.setText(_translate("ReviewDialog", "Accept Changes?"))
        self.accept_button.setText(_translate("ReviewDialog", "Accept"))
        self.decline_button.setText(_translate("ReviewDialog", "Decline"))
